name: Despliegue Blue-Green

# Se activa cada vez que hay un push a la rama 'main'
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Ejecutar despliegue vía SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # 1. Ir a la carpeta del proyecto en el servidor
            cd /root/practica

            # 2. Descargar los últimos cambios de GitHub
            echo "Descargando cambios..."
            git pull origin main
            # 3. Dar permisos de ejecución (por seguridad)
            chmod +x scripts/deploy.sh

            # 4. Entrar a la carpeta de scripts (según veo en tu imagen, el script asume que está ahí o hace cd ..)
            cd scripts

            # 5. Ejecutar tu script de despliegue
            echo "Iniciando script Blue-Green..."
            ./deploy.sh
